#!/usr/bin/env python3
"""Rebuilds lista/lista.tsv from what the intake has accepted.

    tools/monta-lista.py https://tandem-psi-ten.vercel.app/api/acumulado

It reads the accumulated records over plain HTTP and needs no credential: that
is why api/acumulado.js exists at all. Listing the store directly would need the
read-write token, and putting that token in this repository's secrets would put
a secret where the whole design was trying not to have one.

WHAT IT DOES NOT DO, and this is deliberate: it does not commit. It writes the
file and the workflow around it opens a pull request, so a person sees what is
about to be published. Anybody on the internet can POST a record; a poisoned row
that publishes itself would reach every Tandem on earth on the next download,
which is a worse failure than the same row reaching one machine that then asks
its owner before doing anything with it.
"""
import re
import sys
import urllib.request
from collections import defaultdict

CABECALHO = [
    "# TANDEM-LISTA 1",
    "# The Tandem community list. One program per line, TAB-separated fields.",
    "# Full format: docs/LIST-FORMAT.md",
    "#",
    "# GENERATED by tools/monta-lista.py from the accepted records. Editing this",
    "# file by hand works until the next rebuild overwrites it - fix the intake",
    "# or the exclusions below instead.",
    "#",
    "# The machines column counts REPORTS, not machines. The intake keeps nothing",
    "# that could tell two senders apart, on purpose, so a shop that sends the",
    "# same lesson twice is counted twice. See docs/LIST-FORMAT.md.",
]

# Identities that must never be published, with the reason. This is a list of
# decisions, not a rule about shapes - the same arrangement as EXCECOES in
# tools/conta-literais.py, and for the same reason: an exact value somebody had
# to add on purpose cannot quietly grow to cover honest records.
EXCLUIDAS = {
    # Posted by hand from a development container while proving the intake
    # worked end to end. It is the fingerprint of /bin/ls claiming that
    # vcrun2022 fixed it, which is false about a file that is not a Windows
    # program at all. Publishing it would be the list's first record and a lie.
    "3f376993b2da855c5e6e291da008d5d6": "test record from the intake bring-up",
}

FORMA = re.compile(
    r"^[0-9a-f]{32}\t(32|64|arm64|-)\t\S+\t\S+\t"
    r"(confirmado|so-abriu|reprovado)\t\d+\t\d{4}-\d{2}\t\S+$"
)


def baixa(url):
    req = urllib.request.Request(url, headers={"User-Agent": "tandem-monta-lista"})
    with urllib.request.urlopen(req, timeout=60) as r:
        if r.status != 200:
            raise SystemExit("intake answered %s" % r.status)
        return r.read().decode("utf-8")


def monta(texto):
    """Accepted records -> published rows, and what was left out.

    One row per (identity, arch, verbs, failed, confidence). The client merges
    further than this - t_lista_linha adds rows with the same verbs together and
    drops a verb set more machines rejected than confirmed - so the published
    file does not have to be reduced to one row per program, and should not be:
    the rejections are evidence and deleting them here would hide it.
    """
    grupos = defaultdict(lambda: {"n": 0, "visto": ""})
    recusadas = []
    for linha in texto.splitlines():
        linha = linha.rstrip("\n")
        if not linha or linha.startswith("#"):
            continue
        if not FORMA.match(linha):
            recusadas.append(("malformed", linha))
            continue
        campos = linha.split("\t")
        if campos[0] in EXCLUIDAS:
            recusadas.append(("excluded: " + EXCLUIDAS[campos[0]], linha))
            continue
        chave = (campos[0], campos[1], campos[2], campos[3], campos[4])
        g = grupos[chave]
        g["n"] += int(campos[5])
        if campos[6] > g["visto"]:
            g["visto"] = campos[6]

    linhas = []
    for (ident, arch, verbos, falhos, conf), g in grupos.items():
        linhas.append("\t".join([ident, arch, verbos, falhos, conf,
                                 str(g["n"]), g["visto"], "-"]))
    linhas.sort()
    return linhas, recusadas


def main():
    if len(sys.argv) < 2:
        raise SystemExit("uso: monta-lista.py <url do acumulado>")
    linhas, recusadas = monta(baixa(sys.argv[1]))

    with open("lista/lista.tsv", "w", encoding="utf-8") as f:
        f.write("\n".join(CABECALHO) + "\n")
        for l in linhas:
            f.write(l + "\n")

    # Said out loud rather than dropped. A row that vanishes between the intake
    # and the published file with nothing said is how a list quietly stops
    # describing what people reported.
    print("published %d row(s)" % len(linhas))
    for motivo, linha in recusadas:
        print("left out (%s): %s" % (motivo, linha[:60]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
