#!/usr/bin/env python3
"""Rebuilds lista/lista.tsv from what the intake has accepted.

    tools/monta-lista.py https://tandem-psi-ten.vercel.app/api/acumulado

It reads the accumulated records over plain HTTP and needs no credential: that
is why api/acumulado.js exists at all. Listing the store directly would need the
read-write token, and putting that token in this repository's secrets would put
a secret where the whole design was trying not to have one.

WHAT IT DOES NOT DO, and this is deliberate: it does not commit. It writes the
file and the workflow around it opens a pull request, so a person sees what is
about to be published. Anybody on the internet can POST a record; a poisoned row
that publishes itself would reach every Tandem on earth on the next download,
which is a worse failure than the same row reaching one machine that then asks
its owner before doing anything with it.
"""
import re
import sys
import urllib.request
from collections import defaultdict

CABECALHO = [
    "# TANDEM-LISTA 1",
    "# The Tandem community list. One program per line, TAB-separated fields.",
    "# Full format: docs/LIST-FORMAT.md",
    "#",
    "# GENERATED by tools/monta-lista.py from the accepted records. Editing this",
    "# file by hand works until the next rebuild overwrites it - fix the intake",
    "# or the exclusions below instead.",
    "#",
    "# The machines column counts REPORTS, not machines. The intake keeps nothing",
    "# that could tell two senders apart, on purpose, so a shop that sends the",
    "# same lesson twice is counted twice. See docs/LIST-FORMAT.md.",
]

# Identities that must never be published, with the reason. This is a list of
# decisions, not a rule about shapes - the same arrangement as EXCECOES in
# tools/conta-literais.py, and for the same reason: an exact value somebody had
# to add on purpose cannot quietly grow to cover honest records.
EXCLUIDAS = {
    # Posted by hand from a development container while proving the intake
    # worked end to end. It is the fingerprint of /bin/ls claiming that
    # vcrun2022 fixed it, which is false about a file that is not a Windows
    # program at all. Publishing it would be the list's first record and a lie.
    "3f376993b2da855c5e6e291da008d5d6": "test record from the intake bring-up",
}

# Eight fields, optionally followed by the three appended in 4.9: the Wine and
# winetricks versions and the dedup token. Optional rather than required
# because the published file has to keep carrying rows written by 4.6 clients -
# the format is append-only, so an old row is short, not malformed.
FORMA = re.compile(
    r"^[0-9a-f]{32}\t(32|64|arm64|-)\t\S+\t\S+\t"
    r"(confirmado|entregue|so-abriu|reprovado)\t\d+\t\d{4}-\d{2}\t\S+"
    r"(\t[A-Za-z0-9._-]{1,24}\t[A-Za-z0-9._-]{1,24}\t(-|[0-9a-f]{16}))?$"
)

# A verb name is a NAME, never a command line. This mirrors t_verbo_valido in
# common.sh: begins with a letter or digit, then only letters/digits/_/-,
# 40 chars max. The intake already enforces the field shape, but this is the
# gate that reaches every Tandem at once, so it re-checks rather than trusting
# a row got past the intake unchanged - the queue and the store are both
# plain-text things that get edited.
VERBO = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,39}$")

# winetricks "settings" verbs install cleanly and change the prefix instead of
# delivering a dependency - sandbox strips a prefix's links to $HOME,
# remove_mono takes .NET out, winxp moves the Windows version under an installed
# program's feet. A malicious or careless row naming one of these is the AUR
# "Atomic Arch" threat in miniature: valid-looking, installs without error,
# earns a permanent receipt. The client refuses them at the point of use
# (t_verbo_de_fora_ok asks the installed winetricks), but a human reviewing the
# weekly rebuild PR cannot eyeball a verb's class, so the row is refused HERE
# too - a poisoned row must not reach the file every Tandem downloads. This is
# the hard-coded fallback list from common.sh; CI has no winetricks to ask.
VERBOS_SETTINGS = {
    "sandbox", "isolate_home", "remove_mono", "forcemono", "nocrashdialog",
    "alldlls", "win2k", "win2k3", "win7", "win8", "win81", "win10", "win11",
    "win20", "win30", "win31", "win95", "win98", "winme", "winnt40",
    "winvista", "winxp", "winxp64", "native_mdac", "native_oleaut32",
}


def verbos_seguros(campo):
    """True when every verb in a comma-list is a plain dependency name.

    Returns (ok, motivo). A "-" (no verbs) is fine; anything else must pass the
    shape check and not be a settings verb.
    """
    if campo == "-":
        return True, ""
    for v in campo.split(","):
        if not VERBO.match(v):
            return False, "verb %r is not a plain name" % v[:20]
        if v in VERBOS_SETTINGS:
            return False, "verb %r changes a setting, not a dependency" % v
    return True, ""


def baixa(url):
    req = urllib.request.Request(url, headers={"User-Agent": "tandem-monta-lista"})
    with urllib.request.urlopen(req, timeout=60) as r:
        if r.status != 200:
            raise SystemExit("intake answered %s" % r.status)
        return r.read().decode("utf-8")


def monta(texto):
    """Accepted records -> published rows, and what was left out.

    One row per (identity, arch, verbs, failed, confidence). The client merges
    further than this - t_lista_linha adds rows with the same verbs together and
    drops a verb set more machines rejected than confirmed - so the published
    file does not have to be reduced to one row per program, and should not be:
    the rejections are evidence and deleting them here would hide it.
    """
    grupos = defaultdict(lambda: {"n": 0, "visto": ""})
    recusadas = []
    vistos_dedup = set()
    for linha in texto.splitlines():
        linha = linha.rstrip("\n")
        if not linha or linha.startswith("#"):
            continue
        if not FORMA.match(linha):
            recusadas.append(("malformed", linha))
            continue
        campos = linha.split("\t")
        if campos[0] in EXCLUIDAS:
            recusadas.append(("excluded: " + EXCLUIDAS[campos[0]], linha))
            continue
        # The verbs and the failed-verbs field both name winetricks verbs, and
        # both reach a client that may act on them. A settings verb or a
        # command-shaped name in either one refuses the whole row.
        ok_v, motivo_v = verbos_seguros(campos[2])
        ok_f, motivo_f = verbos_seguros(campos[3])
        if not ok_v or not ok_f:
            recusadas.append(("unsafe verb: " + (motivo_v or motivo_f), linha))
            continue
        # The stack is part of the key since 4.9: merging a report from Wine 8
        # with one from Wine 10 produces a row that was never true anywhere,
        # which is the whole reason those columns exist. A row from before 4.9
        # has no stack and groups under "-", where the client weighs it as
        # "unknown" rather than as "wrong".
        wine = campos[8] if len(campos) > 8 else "-"
        wt = campos[9] if len(campos) > 9 else "-"
        dedup = campos[10] if len(campos) > 10 else "-"
        # One report per (machine, program, lesson). The token cannot link two
        # different programs to one machine, so this deduplicates without the
        # store ever holding something that identifies a sender.
        if dedup != "-":
            marca = (campos[0], campos[2], campos[4], dedup)
            if marca in vistos_dedup:
                recusadas.append(("duplicate report of the same lesson", linha))
                continue
            vistos_dedup.add(marca)
        chave = (campos[0], campos[1], campos[2], campos[3], campos[4], wine, wt)
        g = grupos[chave]
        g["n"] += int(campos[5])
        if campos[6] > g["visto"]:
            g["visto"] = campos[6]

    linhas = []
    for (ident, arch, verbos, falhos, conf, wine, wt), g in grupos.items():
        # The dedup token is NOT republished: it did its job at the intake and
        # putting it in a file the whole world downloads would turn a
        # per-program token into something anybody can correlate against.
        linhas.append("\t".join([ident, arch, verbos, falhos, conf,
                                 str(g["n"]), g["visto"], "-", wine, wt, "-"]))
    linhas.sort()
    return linhas, recusadas


def main():
    if len(sys.argv) < 2:
        raise SystemExit("uso: monta-lista.py <url do acumulado>")
    linhas, recusadas = monta(baixa(sys.argv[1]))

    with open("lista/lista.tsv", "w", encoding="utf-8") as f:
        f.write("\n".join(CABECALHO) + "\n")
        for l in linhas:
            f.write(l + "\n")

    # Said out loud rather than dropped. A row that vanishes between the intake
    # and the published file with nothing said is how a list quietly stops
    # describing what people reported.
    print("published %d row(s)" % len(linhas))
    for motivo, linha in recusadas:
        print("left out (%s): %s" % (motivo, linha[:60]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
